# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/fsenzol/C/Video rendering"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/fsenzol/C/Video rendering"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/fsenzol/C/Video rendering/CMakeFiles" "/home/fsenzol/C/Video rendering//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/fsenzol/C/Video rendering/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ascii-renderer

# Build rule for target.
ascii-renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascii-renderer
.PHONY : ascii-renderer

# fast build rule for target.
ascii-renderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/build
.PHONY : ascii-renderer/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/main.c.s
.PHONY : main.c.s

utils/ffmpeg-utils.o: utils/ffmpeg-utils.c.o
.PHONY : utils/ffmpeg-utils.o

# target to build an object file
utils/ffmpeg-utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/utils/ffmpeg-utils.c.o
.PHONY : utils/ffmpeg-utils.c.o

utils/ffmpeg-utils.i: utils/ffmpeg-utils.c.i
.PHONY : utils/ffmpeg-utils.i

# target to preprocess a source file
utils/ffmpeg-utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/utils/ffmpeg-utils.c.i
.PHONY : utils/ffmpeg-utils.c.i

utils/ffmpeg-utils.s: utils/ffmpeg-utils.c.s
.PHONY : utils/ffmpeg-utils.s

# target to generate assembly for a file
utils/ffmpeg-utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ascii-renderer.dir/build.make CMakeFiles/ascii-renderer.dir/utils/ffmpeg-utils.c.s
.PHONY : utils/ffmpeg-utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ascii-renderer"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/ffmpeg-utils.o"
	@echo "... utils/ffmpeg-utils.i"
	@echo "... utils/ffmpeg-utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

